export const FETCH_QUESTION_LOADING = 'FETCH_QUESTION_LOADING';
export const FETCH_QUESTION_FAILED = 'FETCH_QUESTION_FAILED';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';

export const START_TIMER = 'START_TIMER';

export const ADD_RESPONSE_LOADING = 'ADD_RESPONSE_LOADING';
export const ADD_RESPONSE_SUCCESSFUL = 'ADD_RESPONSE_SUCCESSFUL';

export const VERIFY_TEST_SUCCESS = 'VERIFY_TEST_SUCCESS';
export const VERIFY_TEST_FAILED = 'VERIFY_TEST_FAILED';