export const FETCH_QUESTION_LOADING = 'FETCH_QUESTION_LOADING';
export const FETCH_QUESTION_FAILED = 'FETCH_QUESTION_FAILED';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';

export const ADD_RESPONSE_LOADING = 'ADD_RESPONSE_LOADING';
export const ADD_RESPONSE_SUCCESSFUL = 'ADD_RESPONSE_SUCCESSFUL';